
#import <Foundation/Foundation.h>


NS_ASSUME_NONNULL_BEGIN
NS_SWIFT_NAME(DisplayScenario)
typedef NSString *const CRNDisplayScenario NS_TYPED_ENUM;
extern CRNDisplayScenario CRNDisplayScenarioCarmanualInformation;
extern CRNDisplayScenario CRNDisplayScenarioFlightDetail;
extern CRNDisplayScenario CRNDisplayScenarioFreechatConversation;
extern CRNDisplayScenario CRNDisplayScenarioGeoquizSonicWelcome;
extern CRNDisplayScenario CRNDisplayScenarioGeoquizSonicPlay;
extern CRNDisplayScenario CRNDisplayScenarioGeoquizSonicCorrect;
extern CRNDisplayScenario CRNDisplayScenarioGeoquizSonicError;
extern CRNDisplayScenario CRNDisplayScenarioGeoquizSonicEnd;
extern CRNDisplayScenario CRNDisplayScenarioHotelDetail;
extern CRNDisplayScenario CRNDisplayScenarioNaviTripInfo;
extern CRNDisplayScenario CRNDisplayScenarioNaviPoiInfo;
extern CRNDisplayScenario CRNDisplayScenarioPhoneDialingNumber;
extern CRNDisplayScenario CRNDisplayScenarioPhoneSmartListening;
extern CRNDisplayScenario CRNDisplayScenarioRestaurantDetail;
extern CRNDisplayScenario CRNDisplayScenarioSmsComposeMsg;
extern CRNDisplayScenario CRNDisplayScenarioSmsReadMsg;
extern CRNDisplayScenario CRNDisplayScenarioSmsUpdateMsgState;
extern CRNDisplayScenario CRNDisplayScenarioSmsMsgDetail;
extern CRNDisplayScenario CRNDisplayScenarioStockSonicStockInfo;
extern CRNDisplayScenario CRNDisplayScenarioStockDetail;
extern CRNDisplayScenario CRNDisplayScenarioSystemHelp;
extern CRNDisplayScenario CRNDisplayScenarioSystemHomePage;
extern CRNDisplayScenario CRNDisplayScenarioHintsUpdate;
extern CRNDisplayScenario CRNDisplayScenarioHintsAndLeadingQuestionsUpdate;
extern CRNDisplayScenario CRNDisplayScenarioSystemWakeupWord;
extern CRNDisplayScenario CRNDisplayScenarioSystemWuwInputBox;
extern CRNDisplayScenario CRNDisplayScenarioTrainDetail;
extern CRNDisplayScenario CRNDisplayScenarioVehicleControlCarInfo;
extern CRNDisplayScenario CRNDisplayScenarioWeatherInformation;
extern CRNDisplayScenario CRNDisplayScenarioWeatherAqi;
extern CRNDisplayScenario CRNDisplayScenarioFitnessUserResponse;
extern CRNDisplayScenario CRNDisplayScenarioFitnessWorkoutReport;
extern CRNDisplayScenario CRNDisplayScenarioMusicFavoriteList;
extern CRNDisplayScenario CRNDisplayScenarioAudiobookFavoriteList;
extern CRNDisplayScenario CRNDisplayScenarioRadioFavoriteList;
NS_ASSUME_NONNULL_END