
#import <Foundation/Foundation.h>


NS_ASSUME_NONNULL_BEGIN
NS_SWIFT_NAME(FavoriteControlType)
typedef NSString *const CRNFavoriteControlType NS_TYPED_ENUM;
extern CRNFavoriteControlType CRNFavoriteControlTypeAdd;
extern CRNFavoriteControlType CRNFavoriteControlTypeRemove;
NS_ASSUME_NONNULL_END